# Generated by Django 5.1.6 on 2025-03-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="imp_uid",
            field=models.CharField(
                blank=True, help_text="포트원 거래 고유번호", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="merchant_uid",
            field=models.CharField(help_text="주문번호", max_length=100),
        ),
    ]
