# Generated by Django 5.1.6 on 2025-03-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_payment_imp_uid_alter_payment_merchant_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.PositiveIntegerField(help_text="결제 금액"),
        ),
    ]
