# Generated by Django 5.1.6 on 2025-03-20 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_alter_payment_created_at_alter_payment_imp_uid_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="anonymized_user_id",
            field=models.IntegerField(
                blank=True, help_text="익명화된 원본 사용자 ID", null=True
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="is_anonymized",
            field=models.BooleanField(
                default=False, help_text="사용자 탈퇴로 인한 익명화 여부"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
