# Generated by Django 5.1.6 on 2025-03-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_is_admin_alter_user_login_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeletedUserData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_user_id",
                    models.IntegerField(db_index=True, help_text="원래 사용자의 ID"),
                ),
                (
                    "username",
                    models.CharField(help_text="익명화된 사용자명", max_length=150),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="익명화된 이메일",
                        max_length=254,
                        null=True,
                    ),
                ),
                ("deleted_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
