# Generated by Django 5.1.6 on 2025-03-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="duration",
            field=models.IntegerField(
                blank=True, help_text="동영상 길이(분)", null=True
            ),
        ),
    ]
