# Generated by Django 5.1.6 on 2025-03-14 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_lecture_duration"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("option1", models.TextField()),
                ("option2", models.TextField()),
                ("option3", models.TextField()),
                ("option4", models.TextField()),
                ("option5", models.TextField()),
                ("correct_answer", models.IntegerField(help_text="1~5 정답 번호")),
                ("order_index", models.IntegerField(default=0, help_text="문제 순서")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="courses.lecture",
                    ),
                ),
            ],
        ),
    ]
