# Generated by Django 5.1.6 on 2025-03-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_rename_video_url_lecture_video_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="difficulty_level",
            field=models.CharField(
                choices=[
                    ("beginner", "입문"),
                    ("basic", "초급"),
                    ("intermediate", "중급"),
                    ("advanced", "고급"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                db_index=True, decimal_places=0, help_text="원 단위 가격", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="lecture_type",
            field=models.CharField(
                choices=[("video", "동영상"), ("mission", "미션")],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="order_index",
            field=models.IntegerField(db_index=True, help_text="강의 순서"),
        ),
        migrations.AlterField(
            model_name="subject",
            name="order_index",
            field=models.IntegerField(db_index=True, help_text="과목 순서"),
        ),
        migrations.AlterField(
            model_name="subject",
            name="subject_type",
            field=models.CharField(
                choices=[
                    ("normal", "일반"),
                    ("midterm", "중간고사"),
                    ("final", "기말고사"),
                ],
                db_index=True,
                default="normal",
                max_length=20,
            ),
        ),
    ]
