# Generated by Django 5.1.6 on 2025-03-12 07:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "new_users",
                    models.PositiveIntegerField(default=0, help_text="신규 가입자 수"),
                ),
                (
                    "active_users",
                    models.PositiveIntegerField(default=0, help_text="활성 사용자 수"),
                ),
                (
                    "new_enrollments",
                    models.PositiveIntegerField(
                        default=0, help_text="신규 수강 신청 수"
                    ),
                ),
                (
                    "completed_lectures",
                    models.PositiveIntegerField(default=0, help_text="완료된 강의 수"),
                ),
                (
                    "certificates_issued",
                    models.PositiveIntegerField(
                        default=0, help_text="발급된 수료증 수"
                    ),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=0,
                        default=Decimal("0"),
                        help_text="일일 매출액",
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "일별 통계",
                "verbose_name_plural": "일별 통계 목록",
                "ordering": ["-date"],
            },
        ),
    ]
